#!/bin/bash

# Some examples are below and can be simply uncommented for use

echo $HOSTNAME
echo "========================"

# Check for GLSA vulnerabilities
glsa-check -t affected | awk '{ system("glsa-check -p " $1) }'

echo "========================"
