#!/bin/bash

# Some examples are below and can be simply uncommented for use

echo $HOSTNAME
echo "========================"

# Pattern match replace for PAM authentication misconfiguration (disabling GP accounts)
sed -i 's/gp.*/gp[0-9]/' /etc/pam.d/system-auth
cat /etc/pam.d/system-auth | grep pam_lockout

echo "========================"
