#!/bin/bash

# VM launcher
# Jason Gerfen <jason.gerfen@gmail.com>

# Create new if asked
if [ "$1" == "install" ]; then
 if [ -f "$3" ]; then
  dd if=/dev/zero of=vm/$2 bs=516096 seek=9182 count=0
  qemu-system-x86_64 -m 2048 -boot d -cdrom $3 vm/$2 -net nic -net user
  exit
 fi
fi

# Prompt for action
PS3="Select VM to load or 'q' to quit: "

# Get list of VM's
vmList=$(find vm/*.iso -type f)

# Load existing based on user input
select vmName in $vmList; do
 if [ -n "${vmName}" ]; then
  ssh=$(ps xaf | grep qemu-system-x86_64 | awk '{ if ($22 != "") { split($22, a, ":"); ssh=a[2]+1  } else { ssh=2222 } } END { print ssh }')
  http=$(ps xaf | grep qemu-system-x86_64 | awk '{ if ($24 != "") { split($24, a, ":"); http=a[2]+1  } else { http=8080 } } END { print http }')
  https=$(ps xaf | grep qemu-system-x86_64 | awk '{ if ($26 != "") { split($26, a, ":"); https=a[2]+1  } else { https=4343 } } END { print https }')
  n1=$(ps xaf | grep qemu-system-x86_64 | awk '{ if ($28 != "") { split($28, a, ":"); n1=a[2]+1  } else { n1=3000 } } END { print n1 }')
  n2=$(ps xaf | grep qemu-system-x86_64 | awk '{ if ($30 != "") { split($30, a, ":"); n2=a[2]+1  } else { n2=8000 } } END { print n2 }')
  vnc=$(ps xaf | grep qemu-system-x86_64 | awk '{ if ($32 != "") { split($32, a, ":"); vnc=a[2]+1  } else { vnc=1 } } END { print vnc }')
  qemu-system-x86_64 -cpu host -smp cores=8,threads=4,sockets=1 -m 1024 ${vmName} -net user,vlan=0,net=10.0.2.0/24 -net nic,vlan=0 -net user,vlan=1,net=192.168.2.0/25 -net nic,vlan=1 -redir tcp:${ssh}::22 -redir tcp:${http}::80 -redir tcp:${https}::443 -redir tcp:${n1}::3000 -redir tcp:${n2}::8000 -vnc 127.0.0.1:${vnc} -daemonize
 fi
 break
done
exit
